//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// Minimal example showing how to load an eBPF LSM program
// and read events from a ring buffer.
//
// Build:
//   cd examples/basic-capture && go build -o capture .
//
// Run (requires root):
//   sudo ./capture

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -target bpf -I../../kernel/include" bpf ../../kernel/bpf/lsm_hooks.bpf.c

func main() {
	// Allow the current process to lock memory for eBPF maps
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	// Load pre-compiled BPF programs and maps (generated by bpf2go)
	objs := &bpfObjects{}
	if err := loadBpfObjects(objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	// Attach LSM hooks
	lsmHooks := []struct {
		prog *ebpf.Program
		name string
	}{
		{objs.ProbeFileOpen, "file_open"},
		{objs.ProbeBprmCheck, "bprm_check_security"},
	}

	for _, h := range lsmHooks {
		lnk, err := link.AttachLSM(link.LSMOptions{Program: h.prog})
		if err != nil {
			log.Fatalf("attach %s: %v", h.name, err)
		}
		defer lnk.Close()
		fmt.Printf("  attached LSM hook: %s\n", h.name)
	}

	// Open ring buffer
	rb, err := ringbuf.NewReader(objs.Rb)
	if err != nil {
		log.Fatalf("ringbuf: %v", err)
	}
	defer rb.Close()

	fmt.Println("\nListening for provenance events (Ctrl+C to stop)...")

	// Handle signals
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sig
		fmt.Println("\nshutting down...")
		rb.Close()
	}()

	// Read loop
	var count int
	for {
		record, err := rb.Read()
		if err != nil {
			if err == ringbuf.ErrClosed {
				break
			}
			log.Printf("read error: %v", err)
			continue
		}
		count++
		// In production: parse record.RawSample into struct event
		fmt.Printf("[%d] received %d bytes from ringbuf\n",
			count, len(record.RawSample))
	}

	fmt.Printf("Captured %d total events.\n", count)
}
