#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import json
import re
from pathlib import Path


SCHEMA = "providapt.secret_backend_bundle.v1"


def load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"{path}:{line_no}: expected KEY=VALUE")
        key, value = line.split("=", 1)
        key = key.strip().lstrip("\ufeff")
        value = value.strip().strip('"').strip("'")
        if not re.match(r"^[A-Z][A-Z0-9_]*$", key):
            raise SystemExit(f"{path}:{line_no}: invalid env key {key!r}")
        values[key] = value
    if not values:
        raise SystemExit(f"{path}: no environment variables found")
    return values


def redact(value: str, enabled: bool) -> str:
    if not enabled:
        return value
    if len(value) <= 8:
        return "<redacted>"
    return value[:4] + "<redacted>" + value[-4:]


def render_systemd(env_file: str, credential_dir: str, keys: list[str]) -> str:
    lines = [
        "# /etc/systemd/system/providapt.service.d/20-secrets.conf",
        "# Generated by ProvidAPT. Review paths before applying.",
        "[Service]",
        f"EnvironmentFile={env_file}",
        f"ReadWritePaths={credential_dir}",
    ]
    for key in keys:
        lines.append(f"# Optional systemd credential file: {credential_dir}/{key}")
    return "\n".join(lines) + "\n"


def render_docker(env_file: str) -> str:
    return "\n".join([
        "# docker-compose.secrets.override.yml",
        "services:",
        "  providapt:",
        "    env_file:",
        f"      - {env_file}",
        "    secrets:",
        "      - providapt_runtime_secrets",
        "secrets:",
        "  providapt_runtime_secrets:",
        f"    file: {env_file}",
        "",
    ])


def render_kubernetes(name: str, namespace: str, values: dict[str, str], redacted: bool) -> str:
    lines = [
        "apiVersion: v1",
        "kind: Secret",
        "metadata:",
        f"  name: {name}",
        f"  namespace: {namespace}",
        "type: Opaque",
        "data:",
    ]
    for key in sorted(values):
        value = redact(values[key], redacted)
        encoded = base64.b64encode(value.encode("utf-8")).decode("ascii")
        lines.append(f"  {key}: {encoded}")
    lines.extend([
        "---",
        "apiVersion: apps/v1",
        "kind: Deployment",
        "metadata:",
        "  name: providapt",
        f"  namespace: {namespace}",
        "spec:",
        "  template:",
        "    spec:",
        "      containers:",
        "        - name: providapt",
        "          envFrom:",
        "            - secretRef:",
        f"                name: {name}",
        "",
    ])
    return "\n".join(lines)


def render_vault_policy(mount: str, path_prefix: str) -> str:
    secret_path = f"{mount.rstrip('/')}/data/{path_prefix.strip('/')}"
    metadata_path = f"{mount.rstrip('/')}/metadata/{path_prefix.strip('/')}"
    return "\n".join([
        "# providapt-vault-policy.hcl",
        "# Apply with: vault policy write providapt-runtime providapt-vault-policy.hcl",
        f'path "{secret_path}/*" {{',
        '  capabilities = ["read"]',
        "}",
        f'path "{metadata_path}/*" {{',
        '  capabilities = ["list", "read"]',
        "}",
        "",
    ])


def render_vault_loader(mount: str, path_prefix: str, values: dict[str, str], redacted: bool) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Review values before running. Requires VAULT_ADDR and authentication.",
    ]
    for key in sorted(values):
        value = redact(values[key], redacted)
        lines.append(
            "vault kv put "
            f"{mount.rstrip('/')}/{path_prefix.strip('/')}/{key} "
            f"value={json.dumps(value)}"
        )
    lines.append("")
    return "\n".join(lines)


def render_vault_config(mount: str, path_prefix: str, values: dict[str, str]) -> str:
    lines = [
        "# providapt-vault.config.yaml",
        "# Merge into providapt.toml/yaml after a secure config-management system",
        "# has materialized the values or the runtime resolver is wired to Vault.",
        "secrets:",
        "  provider: vault",
        "  vault:",
    ]
    for key in sorted(values):
        lines.append(f"    {path_prefix.strip('/')}/{key}: vault:{mount.rstrip('/')}/{path_prefix.strip('/')}/{key}")
    lines.append("")
    return "\n".join(lines)


def write_bundle(args: argparse.Namespace) -> dict[str, object]:
    env_path = Path(args.env_file)
    values = load_env(env_path)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    redacted = not args.include_values
    files = {
        "systemd_dropin": out_dir / "providapt-secrets.systemd.conf",
        "docker_compose": out_dir / "docker-compose.secrets.override.yml",
        "kubernetes_secret": out_dir / "providapt-runtime-secrets.yaml",
        "vault_policy": out_dir / "providapt-vault-policy.hcl",
        "vault_loader": out_dir / "providapt-vault-load.sh",
        "vault_config": out_dir / "providapt-vault.config.yaml",
        "manifest": out_dir / "secret-backend-manifest.json",
    }
    files["systemd_dropin"].write_text(render_systemd(args.install_env_path, args.systemd_credential_dir, sorted(values)), encoding="utf-8")
    files["docker_compose"].write_text(render_docker(args.install_env_path), encoding="utf-8")
    files["kubernetes_secret"].write_text(render_kubernetes(args.k8s_secret_name, args.k8s_namespace, values, redacted), encoding="utf-8")
    files["vault_policy"].write_text(render_vault_policy(args.vault_mount, args.vault_path_prefix), encoding="utf-8")
    files["vault_loader"].write_text(render_vault_loader(args.vault_mount, args.vault_path_prefix, values, redacted), encoding="utf-8")
    files["vault_loader"].chmod(0o700)
    files["vault_config"].write_text(render_vault_config(args.vault_mount, args.vault_path_prefix, values), encoding="utf-8")
    manifest = {
        "schema": SCHEMA,
        "source_env_file": str(env_path),
        "redacted": redacted,
        "variable_count": len(values),
        "variables": sorted(values),
        "secret_backends": ["systemd", "docker_compose", "kubernetes", "vault"],
        "vault": {
            "mount": args.vault_mount,
            "path_prefix": args.vault_path_prefix,
        },
        "outputs": {key: str(path) for key, path in files.items() if key != "manifest"},
        "warnings": [
            "Generated Kubernetes Secret data is redacted by default; rerun with --include-values only in a secure pipeline.",
            "Generated Vault loader values are redacted by default; rerun with --include-values only in a secure pipeline.",
            "Do not commit filled secret backend artifacts.",
        ],
    }
    files["manifest"].write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description="Render concrete secret backend handoff artifacts.")
    parser.add_argument("--env-file", required=True)
    parser.add_argument("--out-dir", default="build/secrets")
    parser.add_argument("--install-env-path", default="/etc/providapt/providapt.secrets.env")
    parser.add_argument("--systemd-credential-dir", default="/etc/providapt/credentials")
    parser.add_argument("--k8s-secret-name", default="providapt-runtime-secrets")
    parser.add_argument("--k8s-namespace", default="providapt")
    parser.add_argument("--vault-mount", default="secret")
    parser.add_argument("--vault-path-prefix", default="providapt/runtime")
    parser.add_argument("--include-values", action="store_true", help="Write actual secret values into Kubernetes Secret data")
    args = parser.parse_args()
    manifest = write_bundle(args)
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
