// Copyright (c) 2026 Chaoqun-Guo
// SPDX-License-Identifier: Apache-2.0

package releasecheck

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteReport writes the release check report as JSON or Markdown.
// The output format is selected by file extension: .json writes structured
// JSON, everything else writes Markdown suitable for release evidence.
func WriteReport(path string, report Report) error {
	if strings.TrimSpace(path) == "" {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("create report directory: %w", err)
	}

	var data []byte
	var err error
	if strings.EqualFold(filepath.Ext(path), ".json") {
		data, err = json.MarshalIndent(report, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal report: %w", err)
		}
		data = append(data, '\n')
	} else {
		data = []byte(RenderMarkdown(report))
	}

	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("write report: %w", err)
	}
	return nil
}

// RenderMarkdown renders a human-readable release evidence report.
func RenderMarkdown(report Report) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# ProvidAPT Release Evidence\n\n")
	fmt.Fprintf(&b, "Generated by `providaptctl -release-check` for commercial release sign-off.\n\n")

	fmt.Fprintf(&b, "## Release Identity\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n")
	fmt.Fprintf(&b, "|---|---|\n")
	fmt.Fprintf(&b, "| Generated At | %s |\n", report.GeneratedAt.Format("2006-01-02T15:04:05Z07:00"))
	fmt.Fprintf(&b, "| Config Path | `%s` |\n", escapePipe(report.ConfigPath))
	if report.EvidencePath != "" {
		fmt.Fprintf(&b, "| Evidence Path | `%s` |\n", escapePipe(report.EvidencePath))
	}
	if report.WaiverPath != "" {
		fmt.Fprintf(&b, "| Waiver Path | `%s` |\n", escapePipe(report.WaiverPath))
	}
	if report.ChecksumsPath != "" {
		fmt.Fprintf(&b, "| Checksums Path | `%s` |\n", escapePipe(report.ChecksumsPath))
	}
	if report.ChecksumsSignaturePath != "" {
		fmt.Fprintf(&b, "| Checksums Signature Path | `%s` |\n", escapePipe(report.ChecksumsSignaturePath))
	}
	if report.ArtifactsDir != "" {
		fmt.Fprintf(&b, "| Artifacts Dir | `%s` |\n", escapePipe(report.ArtifactsDir))
	}
	if len(report.RequiredArtifactTypes) > 0 {
		fmt.Fprintf(&b, "| Required Artifacts | `%s` |\n", escapePipe(strings.Join(report.RequiredArtifactTypes, ", ")))
	}
	if len(report.SBOMPaths) > 0 {
		fmt.Fprintf(&b, "| SBOM Paths | `%s` |\n", escapePipe(strings.Join(report.SBOMPaths, ", ")))
	}
	fmt.Fprintf(&b, "| Version | `%s` |\n", escapePipe(report.Version))
	fmt.Fprintf(&b, "| Commit | `%s` |\n", escapePipe(report.Commit))
	fmt.Fprintf(&b, "| Build Date | `%s` |\n", escapePipe(report.BuildDate))
	fmt.Fprintf(&b, "| Summary | %s |\n", escapePipe(report.Summary()))
	fmt.Fprintf(&b, "| Release Ready | %t |\n", report.ReleaseReady)
	fmt.Fprintf(&b, "| Commercial Ready | %t |\n\n", report.CommercialReady)

	fmt.Fprintf(&b, "## P0 Gates\n\n")
	fmt.Fprintf(&b, "| Gate | Status | Evidence |\n")
	fmt.Fprintf(&b, "|---|---|---|\n")
	for _, gate := range []string{"config_valid", "version_metadata", "release_evidence", "release_checksums", "release_artifact_matrix", "release_artifact_hashes", "release_checksums_signature", "release_sbom"} {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", gate, strings.ToUpper(bestStatus(report.Checks, gate)), escapePipe(joinCheckMessages(report.Checks, gate)))
	}
	fmt.Fprintf(&b, "\n")

	fmt.Fprintf(&b, "## Checks\n\n")
	fmt.Fprintf(&b, "| Status | Check | Message | Fix Suggestion | Waiver |\n")
	fmt.Fprintf(&b, "|---|---|---|---|---|\n")
	for _, check := range report.Checks {
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s |\n",
			strings.ToUpper(check.Status),
			escapePipe(check.Name),
			escapePipe(check.Message),
			escapePipe(check.FixSuggestion),
			escapePipe(formatWaiver(check.Waiver)),
		)
	}
	return b.String()
}

func bestStatus(checks []Check, name string) string {
	status := "not_run"
	for _, check := range checks {
		if check.Name != name {
			continue
		}
		switch check.Status {
		case StatusFail:
			return StatusFail
		case StatusWarn:
			status = StatusWarn
		case StatusWaived:
			if status != StatusWarn {
				status = StatusWaived
			}
		case StatusPass:
			if status == "not_run" {
				status = StatusPass
			}
		}
	}
	return status
}

func joinCheckMessages(checks []Check, name string) string {
	var messages []string
	for _, check := range checks {
		if check.Name == name {
			messages = append(messages, check.Message)
		}
	}
	if len(messages) == 0 {
		return "not supplied"
	}
	return strings.Join(messages, "; ")
}

func formatWaiver(waiver *Waiver) string {
	if waiver == nil {
		return ""
	}
	parts := []string{
		fmt.Sprintf("approved by %s", waiver.ApprovedBy),
		fmt.Sprintf("reason: %s", waiver.Reason),
	}
	if waiver.Expires != "" {
		parts = append(parts, fmt.Sprintf("expires: %s", waiver.Expires))
	}
	return strings.Join(parts, "; ")
}

func escapePipe(value string) string {
	value = strings.ReplaceAll(value, "\r\n", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.ReplaceAll(value, "|", "\\|")
}
