// Copyright (c) 2026 Chaoqun-Guo
// SPDX-License-Identifier: Apache-2.0

// Package backtrace implements retrospective provenance tracing.
//
// Given a suspicious file inode or process PID, it walks backward
// through the provenance graph — across both the in-memory DAG and
// RocksDB cold storage — to reconstruct the full attack causation
// chain up to the root process or network input source.
//
// Algorithm:
//
//	BFS backward from the starting entity, following reverse edges
//	(edges whose Target == current node).  Each BFS depth level forms
//	a TraceSegment, enabling depth-limited, paginated results.
//
// PROV reverse semantics:
//
//	used(a, e)           → e was used BY a          → a is ancestor of e
//	wasGeneratedBy(e, a) → e was generated BY a     → a is ancestor of e
//	wasInformedBy(a2,a1) → a2 was informed BY a1   → a1 is ancestor of a2
package backtrace

import (
	"fmt"
	"sort"
	"strings"
	"sync"

	"github.com/Chaoqun-Guo/ProvidAPT/internal/engine/provenance"
	"github.com/Chaoqun-Guo/ProvidAPT/internal/storage/store"
)

// ═══════════════════════════════════════════════════════════════
// Constants
// ═══════════════════════════════════════════════════════════════

const (
	defaultMaxDepth = 10
	defaultMaxNodes = 1000
)

// rootProcessIDs are node IDs that stop backward traversal.
var rootProcessIDs = map[string]bool{
	"p:1": true, // systemd / init
	"p:0": true, // kernel idle
}

// ═══════════════════════════════════════════════════════════════
// TraceRequest / TraceResult
// ═══════════════════════════════════════════════════════════════

type TraceRequest struct {
	// StartID is the node ID to begin tracing from.
	// Examples: "p:1234" (process), "f:99999:8:3" (file)
	StartID string `json:"start_id"`

	// MaxDepth limits backward recursion (default 10).
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxNodesPerSegment limits pagination within each depth level.
	MaxNodesPerSegment int `json:"max_nodes_per_segment,omitempty"`

	// SegmentOffset requests a specific segment offset (0-based).
	// 0 = first page, -1 = all segments.
	SegmentOffset int `json:"segment_offset,omitempty"`
}

func (r *TraceRequest) normalize() {
	if r.MaxDepth <= 0 {
		r.MaxDepth = defaultMaxDepth
	}
	if r.MaxNodesPerSegment <= 0 {
		r.MaxNodesPerSegment = defaultMaxNodes
	}
}

// TraceResult contains the complete backward trace output.
type TraceResult struct {
	StartID    string          `json:"start_id"`
	MaxDepth   int             `json:"max_depth"`
	Segments   []*TraceSegment `json:"segments,omitempty"`
	TotalNodes int             `json:"total_nodes"`
	TotalEdges int             `json:"total_edges"`
	Truncated  bool            `json:"truncated"`          // hit depth limit
	HitRoot    bool            `json:"hit_root"`           // reached systemd/init
	Timeline   []TimelineEvent `json:"timeline,omitempty"` // chronological summary
}

// TraceSegment is one depth level of the trace chain.
// Depth 0 = the starting entity itself.
type TraceSegment struct {
	Depth        int                `json:"depth"`
	Nodes        []*provenance.Node `json:"nodes"`
	Edges        []*provenance.Edge `json:"edges,omitempty"` // edges entering this depth
	HasMore      bool               `json:"has_more"`
	TotalAtDepth int                `json:"total_at_depth"`
	Description  string             `json:"description,omitempty"`
}

// TimelineEvent is a single chronological step in the trace.
type TimelineEvent struct {
	Depth       int    `json:"depth"`
	NodeID      string `json:"node_id"`
	NodeLabel   string `json:"node_label"`
	NodeSubtype string `json:"node_subtype"`
	EdgeRel     string `json:"edge_relation,omitempty"`
	Timestamp   string `json:"timestamp,omitempty"`
}

// ═══════════════════════════════════════════════════════════════
// Backtracer
// ═══════════════════════════════════════════════════════════════

// Backtracer walks the provenance graph backward from a starting
// entity, querying both the in-memory DAG and the persistent store.
type Backtracer struct {
	graph *provenance.Graph
	store *store.Store

	// in-memory reverse index (built on each Trace call)
	inMemReverse map[string][]*provenance.Edge
	// cached node lookups
	nodeCache map[string]*provenance.Node
	mu        sync.Mutex
}

// New creates a Backtracer attached to a provenance graph and store.
func New(graph *provenance.Graph, st *store.Store) *Backtracer {
	return &Backtracer{
		graph: graph,
		store: st,
	}
}

// ── Trace ───────────────────────────────────────────────────

// Trace performs a backward provenance trace starting from the
// entity identified by StartID in the request.
//
// The algorithm uses BFS, so segments are ordered by depth
// (0 = start node, 1 = one hop back, etc.), making it natural
// for the caller to iterate depth by depth.
func (bt *Backtracer) Trace(req *TraceRequest) (*TraceResult, error) {
	req.normalize()
	if req.StartID == "" {
		return nil, fmt.Errorf("backtrace: StartID is required")
	}

	bt.mu.Lock()
	// Build in-memory reverse index from the current graph state
	bt.buildReverseIndex()
	bt.mu.Unlock()

	result := &TraceResult{
		StartID:  req.StartID,
		MaxDepth: req.MaxDepth,
	}

	// BFS backward
	type bfsItem struct {
		nodeID   string
		depth    int
		parentID string
		inEdge   *provenance.Edge
	}

	visited := make(map[string]int) // nodeID → depth (first visit wins)
	levels := make(map[int][]bfsItem)

	queue := []bfsItem{{nodeID: req.StartID, depth: 0}}
	visited[req.StartID] = 0

	for len(queue) > 0 {
		item := queue[0]
		queue = queue[1:]

		levels[item.depth] = append(levels[item.depth], item)

		// Stop at max depth
		if item.depth >= req.MaxDepth {
			result.Truncated = true
			continue // don't enqueue children
		}

		// Stop at root processes
		if rootProcessIDs[item.nodeID] {
			result.HitRoot = true
			continue
		}

		// Find reverse edges (ancestors)
		ancestors := bt.reverseEdges(item.nodeID)

		for _, edge := range ancestors {
			ancestorID := edge.Source
			if _, seen := visited[ancestorID]; seen {
				continue
			}
			visited[ancestorID] = item.depth + 1
			queue = append(queue, bfsItem{
				nodeID:   ancestorID,
				depth:    item.depth + 1,
				parentID: item.nodeID,
				inEdge:   edge,
			})
		}
	}

	// Build segments
	for depth := 0; depth <= req.MaxDepth; depth++ {
		items, ok := levels[depth]
		if !ok || len(items) == 0 {
			break
		}

		seg := &TraceSegment{
			Depth:        depth,
			TotalAtDepth: len(items),
		}

		// Paginate within this depth
		off := 0
		if req.SegmentOffset > 0 {
			off = req.SegmentOffset
		}
		end := off + req.MaxNodesPerSegment
		if end > len(items) {
			end = len(items)
		}
		seg.HasMore = end < len(items)

		for _, item := range items[off:end] {
			node := bt.lookupNode(item.nodeID)
			if node != nil {
				seg.Nodes = append(seg.Nodes, node)
			}
			if item.inEdge != nil {
				seg.Edges = append(seg.Edges, item.inEdge)
			}
		}

		switch depth {
		case 0:
			seg.Description = fmt.Sprintf("Start: %s", req.StartID)
		case 1:
			seg.Description = "Direct ancestors (1 hop)"
		default:
			seg.Description = fmt.Sprintf("Ancestors (%d hops)", depth)
		}

		result.Segments = append(result.Segments, seg)
	}

	// Count totals
	for _, seg := range result.Segments {
		result.TotalNodes += len(seg.Nodes)
		result.TotalEdges += len(seg.Edges)
	}

	// Build timeline
	result.Timeline = bt.buildTimeline(result)

	return result, nil
}

// ── Reverse edge lookup ─────────────────────────────────────

// reverseEdges returns all edges whose Target == nodeID.
// Queries both the in-memory reverse index and RocksDB.
func (bt *Backtracer) reverseEdges(nodeID string) []*provenance.Edge {
	seen := make(map[string]bool)
	var out []*provenance.Edge

	// 1. In-memory reverse index
	for _, e := range bt.inMemReverse[nodeID] {
		if !seen[e.ID] {
			seen[e.ID] = true
			out = append(out, e)
		}
	}

	// 2. RocksDB reverse index (if store available)
	if bt.store != nil {
		storeEdges, err := bt.store.GetEdgesByTarget(nodeID)
		if err == nil {
			for _, e := range storeEdges {
				if !seen[e.ID] {
					seen[e.ID] = true
					out = append(out, e)
				}
			}
		}
	}

	// Sort by timestamp ascending (oldest first = most fundamental cause)
	sort.Slice(out, func(i, j int) bool {
		return out[i].Timestamp.Before(out[j].Timestamp)
	})

	return out
}

// ── Node lookup ─────────────────────────────────────────────

func (bt *Backtracer) lookupNode(id string) *provenance.Node {
	// Check cache first
	if n, ok := bt.nodeCache[id]; ok {
		return n
	}
	if bt.nodeCache == nil {
		bt.nodeCache = make(map[string]*provenance.Node)
	}

	// Try in-memory graph
	if n, ok := bt.graph.LookupNode(id); ok && n != nil {
		bt.nodeCache[id] = n
		return n
	}

	// Try RocksDB
	if bt.store != nil {
		n, err := bt.store.GetNode(id)
		if err == nil && n != nil {
			bt.nodeCache[id] = n
			return n
		}
	}

	// Fallback: synthetic node
	syn := bt.syntheticNode(id)
	bt.nodeCache[id] = syn
	return syn
}

// syntheticNode creates a minimal node from an ID string for cases
// where the node metadata isn't in the store.
func (bt *Backtracer) syntheticNode(id string) *provenance.Node {
	n := &provenance.Node{ID: id, Attributes: make(map[string]interface{})}
	if strings.HasPrefix(id, "p:") {
		n.ProvType = "prov:Activity"
		n.Subtype = "process"
		n.Label = id
	} else if strings.HasPrefix(id, "f:") {
		n.ProvType = "prov:Entity"
		n.Subtype = "file"
		n.Label = id
	} else {
		n.ProvType = "prov:Entity"
		n.Subtype = "unknown"
		n.Label = id
	}
	return n
}

// ── Reverse index builder ───────────────────────────────────

func (bt *Backtracer) buildReverseIndex() {
	bt.inMemReverse = make(map[string][]*provenance.Edge)
	for _, e := range bt.graph.Edges() {
		bt.inMemReverse[e.Target] = append(bt.inMemReverse[e.Target], e)
	}
}

// ── Timeline builder ────────────────────────────────────────

func (bt *Backtracer) buildTimeline(result *TraceResult) []TimelineEvent {
	// Collect all edges with their nodes
	// Sort by depth (shallower = closer to cause)
	var events []TimelineEvent
	for _, seg := range result.Segments {
		for i, node := range seg.Nodes {
			evt := TimelineEvent{
				Depth:       seg.Depth,
				NodeID:      node.ID,
				NodeLabel:   node.Label,
				NodeSubtype: node.Subtype,
			}
			if i < len(seg.Edges) {
				evt.EdgeRel = seg.Edges[i].Relation
				evt.Timestamp = seg.Edges[i].Timestamp.Format("15:04:05.000")
			}
			events = append(events, evt)
		}
	}
	return events
}

// ── Convenience methods ─────────────────────────────────────

// TraceByInode is a convenience wrapper — starts a trace from
// the file identified by (inode, devMajor, devMinor).
func (bt *Backtracer) TraceByInode(inode uint64, devMajor, devMinor uint32, maxDepth int) (*TraceResult, error) {
	return bt.Trace(&TraceRequest{
		StartID:  provenance.NodeIDFile(inode, devMajor, devMinor),
		MaxDepth: maxDepth,
	})
}

// TraceByPID is a convenience wrapper — starts a trace from
// the process identified by PID.
func (bt *Backtracer) TraceByPID(pid uint32, maxDepth int) (*TraceResult, error) {
	return bt.Trace(&TraceRequest{
		StartID:  provenance.NodeIDProcess(pid),
		MaxDepth: maxDepth,
	})
}
