// Copyright (c) 2026 Chaoqun-Guo
// SPDX-License-Identifier: Apache-2.0

// Package provenance implements a W3C PROV-compliant provenance graph (DAG)
// built from eBPF kernel events.  It models system activity as PROV concepts:
//
//	prov:Activity    — processes (the actors that perform actions)
//	prov:Entity      — files, network endpoints, IPC channels (things acted upon)
//	prov:Agent       — users (future)
//
// Relations follow the PROV-DM specification:
//
//	prov:used(e, a)           — Activity a used Entity e
//	prov:wasGeneratedBy(e, a) — Entity e was generated by Activity a
//	prov:wasInformedBy(a2,a1) — Activity a2 was informed by Activity a1
//
// Event-to-PROV mapping:
//
//	Event                  PROV Pattern
//	─────                  ────────────
//	process_fork   (pid→child)  wasInformedBy(child, parent)
//	process_exec   (pid→bin)    used(process, binary)
//	file_open      (rd)         used(process, file)
//	file_create    (wr+creat)   wasGeneratedBy(file, process)
//	file_modify    (wr)         wasGeneratedBy(file, process)
//	net_connect    (outbound)   used(process, network-ep)
package provenance

import "fmt"

// ─── PROV namespaces ─────────────────────────────────────────
const (
	ProvNamespace = "http://www.w3.org/ns/prov#"

	// Types
	ProvActivity = "prov:Activity"
	ProvEntity   = "prov:Entity"
	ProvAgent    = "prov:Agent"

	// Relations
	ProvUsed               = "prov:used"
	ProvWasGeneratedBy     = "prov:wasGeneratedBy"
	ProvWasInformedBy      = "prov:wasInformedBy"
	ProvWasDerivedFrom     = "prov:wasDerivedFrom"
	ProvHadSecurityContext = "prov:hadSecurityContext"
)

// ─── Sub-types (our extension beyond PROV) ──────────────────
const (
	SubProcess    = "process"
	SubFile       = "file"
	SubNet        = "network"
	SubCredential = "credential"
)

// ─── Public node ID constructors ─────────────────────────

// NodeIDProcess builds a process node ID from a PID.
func NodeIDProcess(pid uint32) string { return nodeID("p", pid) }

// NodeIDFile builds a file node ID from inode + device.
func NodeIDFile(inode uint64, major, minor uint32) string {
	return nodeID("f", inode, major, minor)
}

// NodeIDFilePath builds a file node ID from a path string (fallback).
func NodeIDFilePath(path string) string {
	return nodeID("f", "path", hashStr(path))
}

// hashStr returns a 64-bit FNV-1a hash of s.
func hashStr(s string) uint64 {
	var h uint64 = 14695981039346656037
	for _, c := range []byte(s) {
		h ^= uint64(c)
		h *= 1099511628211
	}
	return h
}

// nodeID builds a deterministic identifier for a node.
// Process:  p:<pid>
// File:     f:<inode>:<major>:<minor>   or   f:path:<hash>
// Network:  n:<addr>:<port>
func nodeID(kind string, parts ...interface{}) string {
	s := kind
	for _, p := range parts {
		s += ":" + fmt.Sprint(p)
	}
	return s
}

// EdgeIDCustom is the public version of edgeID, usable by external
// packages that need to construct edge identifiers (e.g. the merger).
func EdgeIDCustom(relation, source, target string) string {
	return edgeID(relation, source, target)
}

func edgeID(relation, source, target string) string {
	const max = 80
	raw := relation + ":" + source + "->" + target
	// Replace characters that are invalid in XML IDs.
	buf := make([]byte, 0, len(raw))
	for _, c := range []byte(raw) {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '_' || c == '-' || c == ':' {
			buf = append(buf, c)
		} else if c == '>' {
			buf = append(buf, '_') // replace > in -> with _
		} else {
			buf = append(buf, '_')
		}
	}
	if len(buf) > max {
		buf = buf[:max]
	}
	return string(buf)
}
