{
  "kernel": {
    "verbose": false,
    "hooks": [
      "task_alloc",
      "task_free",
      "file_open",
      "bprm_check_security",
      "socket_connect"
    ]
  },
  "output": {
    "dir": "/var/log/providapt",
    "format": "json"
  },
  "capture": {
    "enable_net": true,
    "enable_file": true,
    "enable_proc": true,
    "sensitive_dir": false
  },
  "api": {
    "grpc": ":50051",
    "rest": ":8080"
  }
}
