/* SPDX-License-Identifier: GPL-2.0 */
/* Auto-generated by BTF: bpftool btf dump file /sys/kernel/btf/vmlinux format c */
/* Placeholder - replace with actual vmlinux.h from target kernel */
#ifndef __VMLINUX_H
#define __VMLINUX_H

/* On a real build, this file is auto-generated by:
 *   bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
 *
 * On systems without BTF, generate with pahole or use a minimal BTF file.
 * See kernel/btf/download_btf.sh for fetching BTF for various distros.
 */

#endif /* __VMLINUX_H */
